config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  resource :biometrics, only: [:edit, :update, :create]
  resources :weight_logs, only: [:index, :create, :destroy, :update]
  resources :reminders, only: [:create, :destroy]
  root to: 'home#index'
end

app/models/weight_log.rb
class WeightLog < ApplicationRecord
  belongs_to :biometric
  after_initialize :default_attributes
  validates_uniqueness_of :date, scope: :biometric_id
  after_save :update_biometric

  def self.update_last_or_create(weight)
    self.create!(weight: weight, date: Date.today)
  rescue StandardError => e
    self.order(:date).last.update!(weight: weight)
  end

  private

  def default_attributes
    self.date ||= Date.today
  end

  def update_biometric
    self.biometric.update!(weight: self.weight) if latest?
  end

  def latest?
    date > self.class.maximum(:date)
  end
end

app/controllers/weight_logs_controller.rb
class WeightLogsController < ApplicationController
  def index
    @weight_logs = current_user.biometric.weight_logs.order(:date)
    @from = from
    @to = to
    respond_to do |format|
      format.html { handle_html_index }
      format.csv { handle_csv_index }
    end
  end

  def create
    current_user.biometric.weight_logs.create!(weight_log_params)
    redirect_back fallback_location: root_path
  end

  def update
    WeightLog.find(params[:id]).update!(weight_log_params)
    redirect_back fallback_location: root_path
  end

  def destroy
    WeightLog.find(params[:id]).destroy
    redirect_back fallback_location: root_path
  end

  private

  def handle_html_index
    @charted_weight_logs = WeightLogsToChartData.new(@weight_logs,
                                                     @from, @to).call
  end

  def handle_csv_index
    csv_filename = "weight_logs_#{Date.today}.csv"
    send_data weight_logs_csv_data, filename: csv_filename
  end

  def wrong_dates_order
    flash[:error] = 'From should not be later than to'
    redirect_back fallback_location: root_path, params: { from: @from, to: @to }
  end

  def weight_logs_csv_data
    query = WeightLogsQuery.new(@weight_logs)
    ::WeightLogsToCsv.new(query.between(@from, @to).relation).call
  end

  def weight_log_params
    params.require(:weight_log).permit(:date, :weight)
  end

  def to
    params[:to].present? ? params[:to] : Date.today.to_s
  end

  def from
    params[:from].present? ? params[:from] : 2.weeks.ago.to_date.to_s
  end
end

app/helpers/weight_logs_helper.rb
module WeightLogsHelper
  def local_maxima_and_minima(time_span, biometric)
    logs = WeightLog.where(date: time_span, biometric: biometric)
    WeightLogsMaximaAndMinima.new(logs).call
  end
end

app/views/weight_logs/index.html.haml
= form_tag(weight_logs_path, method: 'get') do
  = label_tag(:from, 'from')
  = date_field_tag :from, @from
  = label_tag(:to, 'to')
  = date_field_tag :to, @to
  = submit_tag 'Update chart', data: { disable_with: false }
  = submit_tag 'CSV', data: { disable_with: false }, formaction: weight_logs_path('csv')
= line_chart @charted_weight_logs

%p
  your tendency breaks:
  = local_maxima_and_minima(@from..@to, current_user.biometric)

= form_for WeightLog.new do |f|
  = f.label :date
  = f.date_field :date
  = f.label :weight
  = f.number_field :weight
  = f.submit

- @weight_logs.each do |log|
  = form_for log do |form|
    = form.label :date
    = form.date_field :date
    = form.label :weight
    = form.number_field :weight
    = form.submit
  = button_to :delete, weight_log_path(log), method: 'delete'